### PR TITLE
Add table of contents

### PR DESCRIPTION
**Pull request by akstrfn**

### CODE REVIEW

**Comment by vmassol** [comment]
Thanks! :)

**Comment by vmassol** [comment]
You might be interested in sending a PR to https://github.com/docker-library/docs/blob/master/xwiki/content.md too for the official image doc. Thx

**Comment by akstrfn** [comment]
I'll submit a PR :)

Btw I made a mistake in the comment for pandoc toc generation. It wont work without ``-s``. So the following command should be correct ``pandoc -f gfm --toc -s README.md -t markdown | sed '/^$/,$d'``

**Comment by vmassol** [comment]
> Btw I made a mistake in the comment for pandoc toc generation. It wont work without -s. So the following command should be correct pandoc -f gfm --toc -s README.md -t markdown | sed '/^$/,$d'

Updated

**Comment by akstrfn** [comment]
Unfortunately docker does not support anchors so its not possible to update content.md docker-library/docs#1376.

**Comment by vmassol** [comment]
snif... :( that's too bad... Thanks for trying!

**Pull request merged**
