### PR TITLE
fix ??? instead utf-8 string

### PR DESCRIPTION
**Pull request by ItgLvb**
http://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/Installation/InstallationWAR/InstallationMySQL/
default

### CODE REVIEW

**Comment by vmassol** [comment]
Thanks @ItgLvb !'ll create a jira issue on jira.xwiki.org and apply it.

**Comment by vmassol** [comment]
@ItgLvb Could you modify simply the files in `templates`? The build will generate the other ones for the various configs. Thanks

**Comment by vmassol** [comment]
Thanks!

**Comment by ItgLvb** [comment]
Glad to help

**Pull request merged**
