### PR TITLE
Add gradle wrapper

### PR DESCRIPTION
**Pull request by vrachieru**

### CODE REVIEW

**Comment by vmassol** [comment]
Thanks. However this looks not quite right to me since you're adding some code that is not part of the purpose of this module. With a similar strategy we could add docker too. That looks like too much maintenance and too much code to me for little benefit. If we apply this there would actually be more gradle code than dockerfile code! :)

WDYT?

**Comment by vmassol** [comment]
I've never liked the idea of including binaries in the SCM. Now I'm new to gradle and if this is the best practice and everyone agrees, I could be convinced I guess.

**Comment by vmassol** [comment]
Also, I didn't need a full build system for the need. Initially I thought of doing this with a shell script but then I thought it would be a good way to start learning about gradle at the same time. This is just to say that this is not the build for the project but  simple generator.

**Comment by vrachieru** [comment]
Well, you can take it or leave it. I have no desire to impose anything.
As far as I know it's a pretty standard use of Gradle.
As for the maintenance there really isn't any I know of, it's pretty much a none time thing. It needs to be regenerated one you use features from a newer version in your build script (also something that should be stated in build.gradle in a wrapper task).
The way I see it it's a time-saver for contributors as it's not yet another build tool to lookup and install by themselves.

**Comment by vmassol** [comment]
Thanks, I'll gather some more information about this. Right now I'm leaning on the side of not including it but I could well be wrong ;)

**Comment by vmassol** [comment]
I've had @tmortagne ask for this too so I believe you're right.  I've also now explored more gradle and this seems indeed like a best practice in the gradle world.

**Pull request merged**
